version: '3'

services:
  
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    restart: always
    ports:
      - "3030:3030"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:rw
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbroot
    networks:
      - node-network
  
  appnginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
    - "8080:80"
    networks:
      - node-network
    depends_on:
      - db
      - app

networks:
  node-network:
    driver: bridge
